### ISSUE TITLE
Maintenance request unmark complete

### ISSUE THREAD

**Issue by aknight023** [snarfblam/Prop-manager#72]
Add Maintenance method to the Maintenance table (and update UI and API to reflect this). Also, if a Maintenance is marked complete , admin should be able to revert that (e.g. to correct a mistake) if the maintenance request is not completed

**Comment by clarkwmcd** [comment]
Was this code tested? I am getting a 404 error after merging it

**Comment by clarkwmcd** [comment]
Yeah there is no backend API route for the axios post to "/api/changeStatusMaintRequest". Maybe it did not get commited???

**Comment by aknight023** [comment]
#77 should fix it now. Not sure why that wasnt in there #72

**Comment by clarkwmcd** [comment]
Yep its working now. Nice work
